version: '3.8'

services:
  # 1. Serviço da API (Backend Node.js)
  api:
    container_name: portfolio_api_prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    # Adiciona a flag 'host.docker.internal' ao /etc/hosts do container
    # Isso é necessário em algumas versões do Docker no Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Pega os segredos do .env
    env_file:
      - ./backend/.env
    # Sem 'ports' - o NPM falará com ele direto pela rede
    networks:
      - npm_net # Conecta na rede externa
    # Não depende mais do 'db'
    
  # 2. Serviço do Site (Frontend React/Nginx)
  web:
    container_name: portfolio_web_prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    # Sem 'ports' - o NPM falará com ele direto pela rede
    networks:
      - npm_net

# Define a rede externa que já existe
networks:
  npm_net:
    name: host_npm_network
    external: true